# Generated by Django 4.2.7 on 2023-11-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('event_type', models.CharField(choices=[('С индивидуальным участием', 'Individual'), ('Командное участие', 'Team')], default='С индивидуальным участием', max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('place', models.CharField(default='', max_length=150)),
                ('datetime_start', models.BigIntegerField(default=0)),
                ('datetime_end', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('secret_code', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.doc')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='docs',
            field=models.ManyToManyField(through='events.EventDoc', to='docs.doc'),
        ),
    ]
