# Generated by Django 4.2.7 on 2023-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_organizer_eventuser_event_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='secret_code',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
