# Generated by Django 4.2.7 on 2023-12-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_doc_doc_type'),
        ('events', '0006_alter_event_secret_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.BigIntegerField(default=0)),
                ('datetime_end', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Не назначена', 'Not Assigned'), ('В исполнении', 'Active'), ('Завершена', 'Completed')], default='Не назначена', max_length=50)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_event', to='events.event')),
                ('field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.docfield')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.task')),
            ],
        ),
    ]
