# Generated by Django 4.2.7 on 2023-12-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_usertask_task_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='event',
        ),
        migrations.RemoveField(
            model_name='task',
            name='field',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='docs',
        ),
        migrations.DeleteModel(
            name='EventDoc',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
