# Generated by Django 4.2.7 on 2023-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_task_event_remove_task_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
