# Generated by Django 4.2.7 on 2023-12-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usertask_is_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='is_creator',
        ),
    ]
