# Generated by Django 4.2.7 on 2023-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpassport',
            name='doc_template',
            field=models.CharField(default='', max_length=150),
        ),
    ]
