# Generated by Django 4.2.7 on 2023-11-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_url', models.TextField(default='', max_length=150)),
                ('doc_type', models.CharField(choices=[('Дорожная карта', 'Roadmap'), ('Программа мероприятия', 'Programme'), ('Диаграмма Ганта', 'Gant'), ('Проект сметы', 'Money'), ('Служебная записка', 'Note'), ('Приказ', 'Order'), ('Отчет', 'Report')], default='Программа мероприятия', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_field', to='docs.doc')),
            ],
        ),
    ]
