# Generated by Django 4.2.7 on 2023-12-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_doc_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docfield',
            name='value',
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=300)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_value', to='docs.docfield')),
            ],
        ),
    ]
