# Generated by Django 4.2.7 on 2023-12-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpassport_doc_template'),
        ('events', '0010_remove_task_event_remove_task_field_and_more'),
        ('docs', '0003_remove_docfield_value_fieldvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.BigIntegerField(default=0)),
                ('datetime_end', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Не назначена', 'Not Assigned'), ('В исполнении', 'Active'), ('Завершена', 'Completed')], default='Не назначена', max_length=50)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_event', to='events.event')),
                ('field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.docfield')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.task')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_event', to='events.event'),
        ),
        migrations.AddField(
            model_name='doc',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsible', models.BooleanField(default=False)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(through='docs.UserTask', to='users.userprofile'),
        ),
    ]
