# Generated by Django 4.2.7 on 2023-12-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_name'),
        ('docs', '0006_alter_doc_name_alter_docfield_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event'),
        ),
    ]
