# Generated by Django 4.2.7 on 2023-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_alter_task_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfield',
            name='value',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='FieldValue',
        ),
    ]
