# Generated by Django 4.2.7 on 2023-12-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_docfield_value_delete_fieldvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docfield',
            name='value',
        ),
        migrations.RemoveField(
            model_name='task',
            name='field',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=300)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='docs.docfield')),
            ],
        ),
    ]
