# Generated by Django 4.2.7 on 2023-12-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_remove_docfield_value_remove_task_field_task_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
