# Generated by Django 5.0 on 2024-03-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_alter_docfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfield',
            name='field_type',
            field=models.CharField(choices=[('текстовый', 'Text'), ('дата и время', 'Date'), ('числовой', 'Number')], default='текстовый', max_length=20),
        ),
    ]
