# Generated by Django 5.0 on 2024-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_alter_docfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=20),
        ),
    ]
